### ISSUE TITLE
need jar file

### ISSUE THREAD

**Issue by tk-t0n0y** [moeinfatehi/Backup-Finder#1]
add a jar file

**Comment by jeanchristianp** [comment]
How can I add this plugin to Burp? I need a Jar File, the zip file contains various files and cannot import to burp. help

**Comment by moeinfatehi** [comment]
The jar file is uploaded (BackupFinder.jar)
to add to the burp suite:
Extender -> Extensions -> Add
A new tab will be added to the burp suite.
